"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import { createEngagement, type CreateEngagementInput } from "@/lib/api";
import { fetchSession, type VenomSession } from "@/lib/session";

const concernOptions = [
  "Investor due diligence / SOC2 prep",
  "We just launched and want to check safety",
  "A customer asked us about security",
  "We had a recent incident or scare",
  "Routine startup security check"
];

const ownershipOptions = [
  "I am the founder/owner of this domain",
  "I have written authorization from the domain owner"
];

export default function OnboardPage() {
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [session, setSession] = useState<VenomSession | null>(null);
  const [targetUrl, setTargetUrl] = useState("");
  const [ownershipAssertion, setOwnershipAssertion] = useState(ownershipOptions[0]);
  const [concern, setConcern] = useState(concernOptions[0]);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState("");

  const canNext = useMemo(() => {
    if (step === 0) {
      return /^https?:\/\//i.test(targetUrl.trim());
    }
    if (step === 1) {
      return Boolean(ownershipAssertion);
    }
    if (step === 2) {
      return Boolean(concern);
    }
    return true;
  }, [step, targetUrl, ownershipAssertion, concern]);

  async function ensureSession() {
    if (session) {
      return session;
    }
    const current = await fetchSession();
    if (!current) {
      router.replace("/login");
      return null;
    }
    setSession(current);
    return current;
  }

  async function launchStartupScan() {
    setCreating(true);
    setError("");
    try {
      const currentSession = await ensureSession();
      if (!currentSession) {
        return;
      }

      const parsed = new URL(targetUrl.trim());
      const input: CreateEngagementInput = {
        name: `${parsed.hostname} startup baseline`,
        description:
          "Startup onboarding scan generated by guided flow.",
        targetUrl: targetUrl.trim(),
        targetType: "website",
        autoOrchestrate: true,
        scanProfile: "startup",
        startupConcern: concern,
        ownershipAssertion
      };
      await createEngagement(currentSession, input);
      router.push("/dashboard");
    } catch (requestError) {
      setError(
        requestError instanceof Error
          ? requestError.message
          : "Unable to start startup scan."
      );
    } finally {
      setCreating(false);
    }
  }

  return (
    <main className="mx-auto flex min-h-screen w-full max-w-3xl items-center px-4 py-8">
      <section className="w-full rounded-3xl border border-slate-800 bg-[#11161d]/95 p-6 shadow-[0_24px_70px_rgba(0,0,0,0.45)]">
        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-lime-300">
          VENOM - Security Scanner for Startups
        </p>
        <h1 className="mt-2 text-3xl font-semibold text-slate-100">
          Zero to First Security Report in Minutes
        </h1>
        <p className="mt-2 text-sm text-slate-400">
          Guided onboarding tuned for technical startup founders.
        </p>

        <div className="mt-6 space-y-4">
          {step === 0 ? (
            <div>
              <p className="text-sm font-semibold text-slate-100">
                1. What is your product URL?
              </p>
              <p className="mt-1 text-xs text-slate-400">
                We only scan what you authorize.
              </p>
              <input
                type="url"
                value={targetUrl}
                onChange={(event) => setTargetUrl(event.target.value)}
                placeholder="https://yourproduct.com"
                className="mt-3 w-full rounded-xl border border-slate-700 bg-slate-900/85 px-3 py-2 text-sm text-slate-100 outline-none placeholder:text-slate-500 focus:border-lime-400 focus:ring-2 focus:ring-lime-500/20"
              />
            </div>
          ) : null}

          {step === 1 ? (
            <div>
              <p className="text-sm font-semibold text-slate-100">
                2. Confirm authorization
              </p>
              <div className="mt-3 space-y-2">
                {ownershipOptions.map((option) => (
                  <label
                    key={option}
                    className="flex cursor-pointer items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/70 px-3 py-2 text-sm text-slate-200"
                  >
                    <input
                      type="radio"
                      name="ownership"
                      value={option}
                      checked={ownershipAssertion === option}
                      onChange={() => setOwnershipAssertion(option)}
                    />
                    {option}
                  </label>
                ))}
              </div>
            </div>
          ) : null}

          {step === 2 ? (
            <div>
              <p className="text-sm font-semibold text-slate-100">
                3. What are you most worried about?
              </p>
              <div className="mt-3 space-y-2">
                {concernOptions.map((option) => (
                  <label
                    key={option}
                    className="flex cursor-pointer items-center gap-2 rounded-lg border border-slate-700 bg-slate-900/70 px-3 py-2 text-sm text-slate-200"
                  >
                    <input
                      type="radio"
                      name="concern"
                      value={option}
                      checked={concern === option}
                      onChange={() => setConcern(option)}
                    />
                    {option}
                  </label>
                ))}
              </div>
            </div>
          ) : null}

          {step === 3 ? (
            <div className="rounded-xl border border-lime-500/45 bg-lime-500/10 p-4">
              <p className="text-sm font-semibold text-lime-200">
                VENOM is ready to launch your startup scan.
              </p>
              <p className="mt-1 text-xs text-lime-100">
                Startup profile applied: read-only probes, non-destructive mode, and
                founder-first reporting.
              </p>
            </div>
          ) : null}
        </div>

        {error ? (
          <p className="mt-4 rounded-lg border border-rose-500/45 bg-rose-500/10 px-3 py-2 text-sm text-rose-200">
            {error}
          </p>
        ) : null}

        <div className="mt-6 flex flex-wrap items-center justify-between gap-2">
          <button
            type="button"
            onClick={() => setStep((prev) => Math.max(0, prev - 1))}
            disabled={step === 0 || creating}
            className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-200 transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
          >
            Back
          </button>

          {step < 3 ? (
            <button
              type="button"
              onClick={() => setStep((prev) => Math.min(3, prev + 1))}
              disabled={!canNext || creating}
              className="rounded-lg border border-lime-500/45 bg-lime-500/10 px-3 py-2 text-sm font-semibold text-lime-200 transition hover:bg-lime-500/20 disabled:cursor-not-allowed disabled:opacity-60"
            >
              Continue
            </button>
          ) : (
            <button
              type="button"
              onClick={() => void launchStartupScan()}
              disabled={creating}
              className="rounded-lg bg-lime-500/90 px-3 py-2 text-sm font-semibold text-slate-950 transition hover:bg-lime-400 disabled:cursor-not-allowed disabled:opacity-70"
            >
              {creating ? "Launching..." : "Start Scan"}
            </button>
          )}
        </div>
      </section>
    </main>
  );
}
