"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import { createEngagement, type CreateEngagementInput } from "@/lib/api";
import { fetchSession, type VenomSession } from "@/lib/session";

const concernOptions = [
  "Investor due diligence / SOC2 prep",
  "We just launched and want to check safety",
  "A customer asked us about security",
  "We had a recent incident or scare",
  "Routine startup security check"
];

const ownershipOptions = [
  "I am the founder/owner of this domain",
  "I have written authorization from the domain owner"
];

function normalizeTarget(value: string) {
  const trimmed = value.trim();
  if (!trimmed) {
    return "";
  }
  if (/^https?:\/\//i.test(trimmed)) {
    return trimmed;
  }
  return `https://${trimmed}`;
}

function getHost(value: string) {
  try {
    return new URL(value).hostname;
  } catch {
    return "";
  }
}

export default function OnboardPage() {
  const router = useRouter();
  const [session, setSession] = useState<VenomSession | null>(null);
  const [targetUrl, setTargetUrl] = useState("");
  const [ownershipAssertion, setOwnershipAssertion] = useState(ownershipOptions[0]);
  const [concern, setConcern] = useState(concernOptions[0]);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState("");

  const normalizedTarget = useMemo(() => normalizeTarget(targetUrl), [targetUrl]);
  const targetHost = useMemo(() => getHost(normalizedTarget), [normalizedTarget]);
  const canLaunch = Boolean(targetHost && ownershipAssertion && concern && !creating);

  async function ensureSession() {
    if (session) {
      return session;
    }
    const current = await fetchSession();
    if (!current) {
      router.replace("/login");
      return null;
    }
    setSession(current);
    return current;
  }

  async function launchStartupScan() {
    setCreating(true);
    setError("");
    try {
      const currentSession = await ensureSession();
      if (!currentSession) {
        return;
      }
      if (!targetHost) {
        setError("Enter a valid product URL, like zeroops.in or https://zeroops.in.");
        return;
      }

      const input: CreateEngagementInput = {
        name: `${targetHost} startup baseline`,
        description: "Startup onboarding scan generated by guided flow.",
        targetUrl: normalizedTarget,
        targetType: "website",
        autoOrchestrate: true,
        scanProfile: "startup",
        startupConcern: concern,
        ownershipAssertion
      };
      const engagement = await createEngagement(currentSession, input);
      router.push(`/dashboard/report/${encodeURIComponent(engagement._id)}`);
    } catch (requestError) {
      setError(
        requestError instanceof Error
          ? requestError.message
          : "Unable to start startup scan."
      );
    } finally {
      setCreating(false);
    }
  }

  return (
    <main className="min-h-screen bg-slate-100 px-4 py-6 text-slate-950 sm:px-6 lg:px-8">
      <section className="mx-auto grid min-h-[calc(100vh-48px)] max-w-7xl items-center gap-6 lg:grid-cols-[0.9fr_1.1fr]">
        <div className="rounded-3xl bg-slate-950 p-8 text-white shadow-xl">
          <p className="text-sm font-semibold uppercase tracking-wide text-blue-300">
            VENOM onboarding
          </p>
          <h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">
            First report without a security maze.
          </h1>
          <p className="mt-4 max-w-xl text-base leading-7 text-slate-300">
            Add one authorized target. VENOM plans the scan, runs safe probes, and turns results into an executive report plus technical evidence.
          </p>

          <div className="mt-8 grid gap-3">
            {[
              "Non-destructive startup scan profile",
              "Automatic report generation",
              "Operator controls stay available after launch"
            ].map((item) => (
              <div key={item} className="flex items-center gap-3 rounded-xl bg-white/8 p-3">
                <span className="h-2.5 w-2.5 rounded-full bg-blue-400" />
                <span className="text-sm text-slate-200">{item}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
          <div className="flex items-center justify-between gap-3 border-b border-slate-200 pb-5">
            <div>
              <p className="text-sm font-semibold text-blue-700">Scan setup</p>
              <h2 className="mt-1 text-2xl font-semibold text-slate-950">Authorize your target</h2>
            </div>
            <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">
              3 steps
            </span>
          </div>

          <div className="mt-6 space-y-6">
            <label className="block">
              <span className="text-sm font-semibold text-slate-800">Product URL</span>
              <input
                type="text"
                value={targetUrl}
                onChange={(event) => setTargetUrl(event.target.value)}
                placeholder="zeroops.in"
                className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-base outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100"
              />
              <span className="mt-2 block text-sm text-slate-500">
                {targetHost ? `VENOM will scan ${normalizedTarget}` : "You can enter a bare domain or a full URL."}
              </span>
            </label>

            <fieldset>
              <legend className="text-sm font-semibold text-slate-800">Authorization</legend>
              <div className="mt-2 grid gap-2">
                {ownershipOptions.map((option) => (
                  <label
                    key={option}
                    className={`flex items-center gap-3 rounded-xl border p-3 text-sm transition ${
                      ownershipAssertion === option
                        ? "border-blue-300 bg-blue-50 text-blue-900"
                        : "border-slate-200 bg-white text-slate-700 hover:bg-slate-50"
                    }`}
                  >
                    <input
                      type="radio"
                      name="ownership"
                      value={option}
                      checked={ownershipAssertion === option}
                      onChange={() => setOwnershipAssertion(option)}
                      className="h-4 w-4 accent-blue-600"
                    />
                    {option}
                  </label>
                ))}
              </div>
            </fieldset>

            <fieldset>
              <legend className="text-sm font-semibold text-slate-800">Main concern</legend>
              <div className="mt-2 grid gap-2 sm:grid-cols-2">
                {concernOptions.map((option) => (
                  <label
                    key={option}
                    className={`flex min-h-16 items-center gap-3 rounded-xl border p-3 text-sm transition ${
                      concern === option
                        ? "border-blue-300 bg-blue-50 text-blue-900"
                        : "border-slate-200 bg-white text-slate-700 hover:bg-slate-50"
                    }`}
                  >
                    <input
                      type="radio"
                      name="concern"
                      value={option}
                      checked={concern === option}
                      onChange={() => setConcern(option)}
                      className="h-4 w-4 accent-blue-600"
                    />
                    {option}
                  </label>
                ))}
              </div>
            </fieldset>
          </div>

          {error ? (
            <p className="mt-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
              {error}
            </p>
          ) : null}

          <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <button
              type="button"
              onClick={() => router.push("/dashboard")}
              className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"
            >
              Go to dashboard
            </button>
            <button
              type="button"
              onClick={() => void launchStartupScan()}
              disabled={!canLaunch}
              className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-slate-300"
            >
              {creating ? "Starting scan..." : "Start secure scan"}
            </button>
          </div>
        </div>
      </section>
    </main>
  );
}
